apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-function
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverless-function
  template:
    metadata:
      labels:
        app: serverless-function
    spec:
      containers:
        - name: serverless-function
          image: joaojoaovf/serverless-function:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
          env:
            - name: REDIS_HOST
              value: "192.168.121.187"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_INPUT_KEY
              valueFrom:
                configMapKeyRef:
                  name: inputkey
                  key: REDIS_INPUT_KEY
            - name: REDIS_OUTPUT_KEY
              valueFrom:
                configMapKeyRef:
                  name: outputkey
                  key: REDIS_OUTPUT_KEY
            - name: MONITORING_PERIOD
              valueFrom:
                configMapKeyRef:
                  name: monitoringperiod
                  key: MONITORING_PERIOD
            - name: ZIP_FILE_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: zipconfig
                  key: ZIP_FILE_LOCATION
          volumeMounts:
            - name: pyfile
              mountPath: "/opt/usermodule.py"
              subPath: pyfile
            - name: zipfile
              mountPath: "/opt/userzip.zip"
              subPath: zipfile
      volumes:
        - name: pyfile
          configMap:
            name: pyfile
        - name: zipfile
          configMap:
            name: zipconfig
